name: prediction-model-compare-prod
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pandas>=2.0.0,<3.0.0
  - numpy>=1.24.0,<2.0.0
  - scikit-learn>=1.3.0,<2.0.0
  - imbalanced-learn>=0.11.0,<1.0.0
  - matplotlib>=3.7.0,<4.0.0
  - seaborn>=0.12.0,<1.0.0
  - python-dotenv>=1.0.0
  - pyyaml>=6.0
  - colorlog>=6.7.0
  # - pytest>=7.4.0,<8.0.0
  # - coverage>=7.0.0,<8.0.0